### ISSUE TITLE
Option to create a Conveyance is not present

### ISSUE THREAD

**Issue by impittman** [impittman/PTC-Inspection-Field-Tool#5] opened 2018-06-11 00:53 UTC
According to the requirements, "The system will allow the user to create a new Conveyance." However, there is no option to add Conveyances under "Collect New" in Collector. This needs to be added.

**Comment by dobrochtaKCI** [comment] 2018-06-11 17:16
Conveyance layer is a part of the same service as Structures, so as far as settings are concerned the conveyance layer should be editable. I noticed this issue when viewing the application using windows collector and Android, however using an Ipad, new conveyances can be added. The conveyances are also editable in the web map as well. The issue is related to the Device Operating systems and not the services.

**Comment by impittman** [comment] 2018-06-11 17:21
@leeensminger if this is a device operating systems issue, how is this to be resolved? I was under the impression this is to be ran in desktop, android and ipad, so it is still an issue with it not showing up correct?

**Comment by dobrochtaKCI** [comment] 2018-06-13 13:44
After spending some time tinkering with the windows version of collector. The Collector Application does allow Conveyance features to be collected using the windows application. The windows application is more strictly enforcing the relationship between the structures and the conveyances(Structure has Conveyance Up and Structure has Conveyance Down) In order to add a conveyance you need to select a structure first and scroll to the bottom of the popup and select to add conveyance. The only issue now is that there are two conveyance options one for the up stream relationship and downstream relationship and there is no way to tell them apart. I will continue to look into this.

**Comment by dobrochtaKCI** [comment] 2018-06-22 03:06
Still working on this, but I am having difficulty publishing data from our migrated database. Data extracted from the database publishes successfully. Not clear what the issue is at this time.

**Comment by leeensminger** [comment] 2018-07-06 20:09
Determined this functionality will be stripped.  New conveyances cannot be created.  Closing issue.

**Closed as completed by leeensminger** 2018-07-06 20:09 UTC
Labels: functional bug, help wanted
